name: Build & Deploy Test Report

# Controls when the action will run. 
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ main ]
    # Only run the workflow if files related to the report in question have been changed
    paths: 
      - 'testReport/**/*'
      - '.github/workflows/testReport.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-deploy"
  build-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: testReport

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Install Dependencies
        run: npm i

      # For some reason, the lambda step fails if there are symlinks in the artifact
      - name: Remove symlinks
        run: rm -rf node_modules/.bin
      
      - name: Typescript Compile
        run: npx tsc -p tsconfig-build.json

      # Deploy build artifact zip file to AWS Lambda and create a new version
      - uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: TestReport
          source: testReport/*
